// Generated by scripts/generate_toolkit_proto_bridge.py.
import Foundation
import InternalSwiftProtobuf
import ToolKit

struct NativeDecodeResult: Codable {
    let swiftType: String
    let protoMessageName: String
    let json: String
    let unknownFieldsHex: String
    let canonicalBinaryHex: String
}

struct NativeProtoName: Codable {
    let number: Int
    let protoName: String
    let jsonName: String?
}

func reflectedOptionalDescription(_ value: Any) -> String? {
    let mirror = Mirror(reflecting: value)
    guard mirror.displayStyle == .optional else {
        return String(describing: value)
    }
    guard let wrapped = mirror.children.first?.value else { return nil }
    return String(describing: wrapped)
}

func nativeNames<T: InternalSwiftProtobuf._ProtoNameProviding>(
    _ type: T.Type
) -> [NativeProtoName] {
    let mapMirror = Mirror(reflecting: T._protobuf_nameMap)
    guard let numberMap = mapMirror.children.first(where: {
        $0.label == "numberToNameMap"
    })?.value else { return [] }

    return Mirror(reflecting: numberMap).children.compactMap { entry in
        let pair = Array(Mirror(reflecting: entry.value).children)
        guard pair.count == 2, let number = pair[0].value as? Int else {
            return nil
        }
        let fields = Dictionary(uniqueKeysWithValues:
            Mirror(reflecting: pair[1].value).children.compactMap { child in
                child.label.map { ($0, child.value) }
            }
        )
        guard let proto = fields["proto"] else { return nil }
        return NativeProtoName(
            number: number,
            protoName: String(describing: proto),
            jsonName: fields["json"].flatMap(reflectedOptionalDescription)
        )
    }.sorted { $0.number < $1.number }
}

struct NativeMessageType {
    let swiftType: String
    let decode: (Data) throws -> NativeDecodeResult
    let names: () -> [NativeProtoName]
    let fields: () -> [NativeFieldSchema]
    let oneofGroups: () -> [[Int]]

    init<M: InternalSwiftProtobuf.Message & InternalSwiftProtobuf._ProtoNameProviding>(
        _ swiftType: String,
        _ type: M.Type
    ) {
        self.swiftType = swiftType
        self.names = { nativeNames(M.self) }
        self.fields = {
            traceSchema(M.self, fieldNumbers: nativeNames(M.self).map(\.number))
        }
        self.oneofGroups = {
            traceOneofGroups(
                M.self,
                fieldNumbers: nativeNames(M.self).map(\.number)
            )
        }
        self.decode = { data in
            let message = try M(serializedBytes: data)
            return NativeDecodeResult(
                swiftType: swiftType,
                protoMessageName: M.protoMessageName,
                json: try message.jsonString(),
                unknownFieldsHex: message.unknownFields.data.hexString,
                canonicalBinaryHex: try message.serializedData(partial: true).hexString
            )
        }
    }
}

struct NativeEnumType {
    let swiftType: String
    let names: () -> [NativeProtoName]

    init<E: InternalSwiftProtobuf.Enum & InternalSwiftProtobuf._ProtoNameProviding>(
        _ swiftType: String,
        _ type: E.Type
    ) {
        self.swiftType = swiftType
        self.names = { nativeNames(E.self) }
    }
}

let nativeMessageTypes: [NativeMessageType] = [
    NativeMessageType("ToolKitProtoAllPredicate", ToolKit.ToolKitProtoAllPredicate.self),
    NativeMessageType("ToolKitProtoAppDefinition", ToolKit.ToolKitProtoAppDefinition.self),
    NativeMessageType("ToolKitProtoAppDefinition.Device", ToolKit.ToolKitProtoAppDefinition.Device.self),
    NativeMessageType("ToolKitProtoAssistantSchemaIdentifier", ToolKit.ToolKitProtoAssistantSchemaIdentifier.self),
    NativeMessageType("ToolKitProtoAssistantSchemaVersion", ToolKit.ToolKitProtoAssistantSchemaVersion.self),
    NativeMessageType("ToolKitProtoAssistantToolSchemaDefinition", ToolKit.ToolKitProtoAssistantToolSchemaDefinition.self),
    NativeMessageType("ToolKitProtoAssistantTypeSchemaDefinition", ToolKit.ToolKitProtoAssistantTypeSchemaDefinition.self),
    NativeMessageType("ToolKitProtoAssistantTypeSchemaDefinition.Entity", ToolKit.ToolKitProtoAssistantTypeSchemaDefinition.Entity.self),
    NativeMessageType("ToolKitProtoAssistantTypeSchemaDefinition.Enumeration", ToolKit.ToolKitProtoAssistantTypeSchemaDefinition.Enumeration.self),
    NativeMessageType("ToolKitProtoChangeset", ToolKit.ToolKitProtoChangeset.self),
    NativeMessageType("ToolKitProtoChangeset.Partial", ToolKit.ToolKitProtoChangeset.Partial.self),
    NativeMessageType("ToolKitProtoChangeset.Provenance", ToolKit.ToolKitProtoChangeset.Provenance.self),
    NativeMessageType("ToolKitProtoCoercionDefinition", ToolKit.ToolKitProtoCoercionDefinition.self),
    NativeMessageType("ToolKitProtoComparisonPredicate", ToolKit.ToolKitProtoComparisonPredicate.self),
    NativeMessageType("ToolKitProtoComparisonPredicate.Comparison", ToolKit.ToolKitProtoComparisonPredicate.Comparison.self),
    NativeMessageType("ToolKitProtoComparisonPredicate.Comparison.Pair", ToolKit.ToolKitProtoComparisonPredicate.Comparison.Pair.self),
    NativeMessageType("ToolKitProtoComparisonPredicate.Comparison.Template", ToolKit.ToolKitProtoComparisonPredicate.Comparison.Template.self),
    NativeMessageType("ToolKitProtoComparisonPredicate.Template", ToolKit.ToolKitProtoComparisonPredicate.Template.self),
    NativeMessageType("ToolKitProtoCompoundPredicate", ToolKit.ToolKitProtoCompoundPredicate.self),
    NativeMessageType("ToolKitProtoContainerDefinition", ToolKit.ToolKitProtoContainerDefinition.self),
    NativeMessageType("ToolKitProtoContainerDefinition.Device", ToolKit.ToolKitProtoContainerDefinition.Device.self),
    NativeMessageType("ToolKitProtoContentItemClassDescriptor", ToolKit.ToolKitProtoContentItemClassDescriptor.self),
    NativeMessageType("ToolKitProtoContentItemClassDescriptor.LinkCodableContentItemClass", ToolKit.ToolKitProtoContentItemClassDescriptor.LinkCodableContentItemClass.self),
    NativeMessageType("ToolKitProtoContentItemClassDescriptor.LinkEntityContentItemClass", ToolKit.ToolKitProtoContentItemClassDescriptor.LinkEntityContentItemClass.self),
    NativeMessageType("ToolKitProtoContentItemClassDescriptor.LinkEnumContentItemClass", ToolKit.ToolKitProtoContentItemClassDescriptor.LinkEnumContentItemClass.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation", ToolKit.ToolKitProtoDisplayRepresentation.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.AltText", ToolKit.ToolKitProtoDisplayRepresentation.AltText.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.AltText.Static", ToolKit.ToolKitProtoDisplayRepresentation.AltText.Static.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.DisplayValue", ToolKit.ToolKitProtoDisplayRepresentation.DisplayValue.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.DisplayValue.Static", ToolKit.ToolKitProtoDisplayRepresentation.DisplayValue.Static.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.Image", ToolKit.ToolKitProtoDisplayRepresentation.Image.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.Image.Static", ToolKit.ToolKitProtoDisplayRepresentation.Image.Static.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.Image.Static.Symbol", ToolKit.ToolKitProtoDisplayRepresentation.Image.Static.Symbol.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.Storage", ToolKit.ToolKitProtoDisplayRepresentation.Storage.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.Subtitle", ToolKit.ToolKitProtoDisplayRepresentation.Subtitle.self),
    NativeMessageType("ToolKitProtoDisplayRepresentation.Subtitle.Static", ToolKit.ToolKitProtoDisplayRepresentation.Subtitle.Static.self),
    NativeMessageType("ToolKitProtoEntityInstanceIdentifier", ToolKit.ToolKitProtoEntityInstanceIdentifier.self),
    NativeMessageType("ToolKitProtoEntityInstanceIdentifier.SyncedIdentifier", ToolKit.ToolKitProtoEntityInstanceIdentifier.SyncedIdentifier.self),
    NativeMessageType("ToolKitProtoFlowToolSchemaIdentifier", ToolKit.ToolKitProtoFlowToolSchemaIdentifier.self),
    NativeMessageType("ToolKitProtoIdSearchPredicate", ToolKit.ToolKitProtoIdSearchPredicate.self),
    NativeMessageType("ToolKitProtoIdSearchPredicate.Template", ToolKit.ToolKitProtoIdSearchPredicate.Template.self),
    NativeMessageType("ToolKitProtoIndexingEvent", ToolKit.ToolKitProtoIndexingEvent.self),
    NativeMessageType("ToolKitProtoIndexingLogEntry", ToolKit.ToolKitProtoIndexingLogEntry.self),
    NativeMessageType("ToolKitProtoIndexingPolicyResolution", ToolKit.ToolKitProtoIndexingPolicyResolution.self),
    NativeMessageType("ToolKitProtoIndexingReason", ToolKit.ToolKitProtoIndexingReason.self),
    NativeMessageType("ToolKitProtoIndexingRequest", ToolKit.ToolKitProtoIndexingRequest.self),
    NativeMessageType("ToolKitProtoIndexingResponse", ToolKit.ToolKitProtoIndexingResponse.self),
    NativeMessageType("ToolKitProtoIndexingStep", ToolKit.ToolKitProtoIndexingStep.self),
    NativeMessageType("ToolKitProtoLaunchServicesSnapshot", ToolKit.ToolKitProtoLaunchServicesSnapshot.self),
    NativeMessageType("ToolKitProtoLaunchServicesSnapshot.State", ToolKit.ToolKitProtoLaunchServicesSnapshot.State.self),
    NativeMessageType("ToolKitProtoLaunchServicesSnapshot.Version", ToolKit.ToolKitProtoLaunchServicesSnapshot.Version.self),
    NativeMessageType("ToolKitProtoLinkSnapshot", ToolKit.ToolKitProtoLinkSnapshot.self),
    NativeMessageType("ToolKitProtoLinkSnapshot.State", ToolKit.ToolKitProtoLinkSnapshot.State.self),
    NativeMessageType("ToolKitProtoModelRepresentation", ToolKit.ToolKitProtoModelRepresentation.self),
    NativeMessageType("ToolKitProtoModelRepresentation.Representation", ToolKit.ToolKitProtoModelRepresentation.Representation.self),
    NativeMessageType("ToolKitProtoModelRepresentation.RepresentationComponent", ToolKit.ToolKitProtoModelRepresentation.RepresentationComponent.self),
    NativeMessageType("ToolKitProtoModelRepresentation.RepresentationComponent.Label", ToolKit.ToolKitProtoModelRepresentation.RepresentationComponent.Label.self),
    NativeMessageType("ToolKitProtoModelRepresentation.RepresentationComponent.TextValue", ToolKit.ToolKitProtoModelRepresentation.RepresentationComponent.TextValue.self),
    NativeMessageType("ToolKitProtoModelRepresentation.RepresentationComponent.VisualValue", ToolKit.ToolKitProtoModelRepresentation.RepresentationComponent.VisualValue.self),
    NativeMessageType("ToolKitProtoModelRepresentation.RepresentationComponent.VisualValue.Transferable", ToolKit.ToolKitProtoModelRepresentation.RepresentationComponent.VisualValue.Transferable.self),
    NativeMessageType("ToolKitProtoPluginModelData", ToolKit.ToolKitProtoPluginModelData.self),
    NativeMessageType("ToolKitProtoPullOperationEnd", ToolKit.ToolKitProtoPullOperationEnd.self),
    NativeMessageType("ToolKitProtoPullOperationStart", ToolKit.ToolKitProtoPullOperationStart.self),
    NativeMessageType("ToolKitProtoPushDonationEnd", ToolKit.ToolKitProtoPushDonationEnd.self),
    NativeMessageType("ToolKitProtoPushDonationStart", ToolKit.ToolKitProtoPushDonationStart.self),
    NativeMessageType("ToolKitProtoQuery", ToolKit.ToolKitProtoQuery.self),
    NativeMessageType("ToolKitProtoQuery.AnyPredicate", ToolKit.ToolKitProtoQuery.AnyPredicate.self),
    NativeMessageType("ToolKitProtoRestrictionContext", ToolKit.ToolKitProtoRestrictionContext.self),
    NativeMessageType("ToolKitProtoRestrictionContext.CharacterTypedWith", ToolKit.ToolKitProtoRestrictionContext.CharacterTypedWith.self),
    NativeMessageType("ToolKitProtoRestrictionContext.InInclusiveRange", ToolKit.ToolKitProtoRestrictionContext.InInclusiveRange.self),
    NativeMessageType("ToolKitProtoRestrictionContext.InSet", ToolKit.ToolKitProtoRestrictionContext.InSet.self),
    NativeMessageType("ToolKitProtoRestrictionContext.InSet.ValueSet", ToolKit.ToolKitProtoRestrictionContext.InSet.ValueSet.self),
    NativeMessageType("ToolKitProtoRestrictionContext.InSet.ValueSet.ContentPropertyPossibleValues", ToolKit.ToolKitProtoRestrictionContext.InSet.ValueSet.ContentPropertyPossibleValues.self),
    NativeMessageType("ToolKitProtoRestrictionContext.InSet.ValueSet.DynamicEnumeration", ToolKit.ToolKitProtoRestrictionContext.InSet.ValueSet.DynamicEnumeration.self),
    NativeMessageType("ToolKitProtoRestrictionContext.InSet.ValueSet.DynamicTriggerEnumeration", ToolKit.ToolKitProtoRestrictionContext.InSet.ValueSet.DynamicTriggerEnumeration.self),
    NativeMessageType("ToolKitProtoRestrictionContext.InSet.ValueSet.LinkQuery", ToolKit.ToolKitProtoRestrictionContext.InSet.ValueSet.LinkQuery.self),
    NativeMessageType("ToolKitProtoRestrictionContext.MeasurementExpressibleAs", ToolKit.ToolKitProtoRestrictionContext.MeasurementExpressibleAs.self),
    NativeMessageType("ToolKitProtoRestrictionContext.RepresentableAs", ToolKit.ToolKitProtoRestrictionContext.RepresentableAs.self),
    NativeMessageType("ToolKitProtoRestrictionContext.TextTypedWith", ToolKit.ToolKitProtoRestrictionContext.TextTypedWith.self),
    NativeMessageType("ToolKitProtoRuntimePlatformVersion", ToolKit.ToolKitProtoRuntimePlatformVersion.self),
    NativeMessageType("ToolKitProtoRuntimeRequirement", ToolKit.ToolKitProtoRuntimeRequirement.self),
    NativeMessageType("ToolKitProtoRuntimeRequirement.AvailabilityAnnotation", ToolKit.ToolKitProtoRuntimeRequirement.AvailabilityAnnotation.self),
    NativeMessageType("ToolKitProtoRuntimeRequirement.DeviceCapability", ToolKit.ToolKitProtoRuntimeRequirement.DeviceCapability.self),
    NativeMessageType("ToolKitProtoRuntimeRequirement.DeviceCapability.MobileGestalt", ToolKit.ToolKitProtoRuntimeRequirement.DeviceCapability.MobileGestalt.self),
    NativeMessageType("ToolKitProtoRuntimeRequirement.FeatureFlag", ToolKit.ToolKitProtoRuntimeRequirement.FeatureFlag.self),
    NativeMessageType("ToolKitProtoSampleInvocationDefinition", ToolKit.ToolKitProtoSampleInvocationDefinition.self),
    NativeMessageType("ToolKitProtoSearchableItemPredicate", ToolKit.ToolKitProtoSearchableItemPredicate.self),
    NativeMessageType("ToolKitProtoSearchableItemPredicate.Template", ToolKit.ToolKitProtoSearchableItemPredicate.Template.self),
    NativeMessageType("ToolKitProtoStringSearchPredicate", ToolKit.ToolKitProtoStringSearchPredicate.self),
    NativeMessageType("ToolKitProtoStringSearchPredicate.Template", ToolKit.ToolKitProtoStringSearchPredicate.Template.self),
    NativeMessageType("ToolKitProtoSuggestedPredicate", ToolKit.ToolKitProtoSuggestedPredicate.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol", ToolKit.ToolKitProtoSystemToolProtocol.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.AgentIntent", ToolKit.ToolKitProtoSystemToolProtocol.AgentIntent.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.AppIntent", ToolKit.ToolKitProtoSystemToolProtocol.AppIntent.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.AssistantSchema", ToolKit.ToolKitProtoSystemToolProtocol.AssistantSchema.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.ConditionallyEnabled", ToolKit.ToolKitProtoSystemToolProtocol.ConditionallyEnabled.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.EntityUpdating", ToolKit.ToolKitProtoSystemToolProtocol.EntityUpdating.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.FlowToolSchema", ToolKit.ToolKitProtoSystemToolProtocol.FlowToolSchema.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.IntentSideEffect", ToolKit.ToolKitProtoSystemToolProtocol.IntentSideEffect.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.IntentSideEffect.Behavior", ToolKit.ToolKitProtoSystemToolProtocol.IntentSideEffect.Behavior.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.IntentSideEffect.StateChangeWithBehavior", ToolKit.ToolKitProtoSystemToolProtocol.IntentSideEffect.StateChangeWithBehavior.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.IntentSideEffectBehavior", ToolKit.ToolKitProtoSystemToolProtocol.IntentSideEffectBehavior.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.IntentSideEffectBehavior.Kind", ToolKit.ToolKitProtoSystemToolProtocol.IntentSideEffectBehavior.Kind.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.IntentStateChange", ToolKit.ToolKitProtoSystemToolProtocol.IntentStateChange.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.PlayVideo", ToolKit.ToolKitProtoSystemToolProtocol.PlayVideo.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.PropertyUpdater", ToolKit.ToolKitProtoSystemToolProtocol.PropertyUpdater.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.ShowInAppStringSearchResults", ToolKit.ToolKitProtoSystemToolProtocol.ShowInAppStringSearchResults.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.SiriKitIntent", ToolKit.ToolKitProtoSystemToolProtocol.SiriKitIntent.self),
    NativeMessageType("ToolKitProtoSystemToolProtocol.SynthesizedToolProtocol", ToolKit.ToolKitProtoSystemToolProtocol.SynthesizedToolProtocol.self),
    NativeMessageType("ToolKitProtoSystemTypeProtocol", ToolKit.ToolKitProtoSystemTypeProtocol.self),
    NativeMessageType("ToolKitProtoSystemTypeProtocol.AssistantSchema", ToolKit.ToolKitProtoSystemTypeProtocol.AssistantSchema.self),
    NativeMessageType("ToolKitProtoSystemTypeProtocol.IntentUpdatableEntity", ToolKit.ToolKitProtoSystemTypeProtocol.IntentUpdatableEntity.self),
    NativeMessageType("ToolKitProtoSystemTypeProtocol.ModelRepresentationMetadata", ToolKit.ToolKitProtoSystemTypeProtocol.ModelRepresentationMetadata.self),
    NativeMessageType("ToolKitProtoSystemTypeProtocol.PersistentFileIdentifiable", ToolKit.ToolKitProtoSystemTypeProtocol.PersistentFileIdentifiable.self),
    NativeMessageType("ToolKitProtoToolDatabaseOpaqueValue", ToolKit.ToolKitProtoToolDatabaseOpaqueValue.self),
    NativeMessageType("ToolKitProtoToolDefinition", ToolKit.ToolKitProtoToolDefinition.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1", ToolKit.ToolKitProtoToolDefinition.Version1.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Category", ToolKit.ToolKitProtoToolDefinition.Version1.Category.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Deprecation", ToolKit.ToolKitProtoToolDefinition.Version1.Deprecation.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.BooleanMetadata", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.BooleanMetadata.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.Contains", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.Contains.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.DoesNotContain", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.DoesNotContain.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.Equals", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.Equals.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.GreaterThan", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.GreaterThan.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.LessThan", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.LessThan.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.NotEquals", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.Relationship.Relation.NotEquals.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.Parameter.ToolMetadata", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.ToolMetadata.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.ToolIcon", ToolKit.ToolKitProtoToolDefinition.Version1.ToolIcon.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.ToolIcon.ToolExternalAsset", ToolKit.ToolKitProtoToolDefinition.Version1.ToolIcon.ToolExternalAsset.self),
    NativeMessageType("ToolKitProtoToolDefinition.Version1.ToolIcon.ToolSymbolIcon", ToolKit.ToolKitProtoToolDefinition.Version1.ToolIcon.ToolSymbolIcon.self),
    NativeMessageType("ToolKitProtoToolDefinitionClosure", ToolKit.ToolKitProtoToolDefinitionClosure.self),
    NativeMessageType("ToolKitProtoToolDefinitionClosure.Version1", ToolKit.ToolKitProtoToolDefinitionClosure.Version1.self),
    NativeMessageType("ToolKitProtoToolInvocation", ToolKit.ToolKitProtoToolInvocation.self),
    NativeMessageType("ToolKitProtoToolInvocationOptions", ToolKit.ToolKitProtoToolInvocationOptions.self),
    NativeMessageType("ToolKitProtoToolInvocationOptions.UserIdentity", ToolKit.ToolKitProtoToolInvocationOptions.UserIdentity.self),
    NativeMessageType("ToolKitProtoToolInvocationSignature", ToolKit.ToolKitProtoToolInvocationSignature.self),
    NativeMessageType("ToolKitProtoToolInvocationSignature.ListOfRelations", ToolKit.ToolKitProtoToolInvocationSignature.ListOfRelations.self),
    NativeMessageType("ToolKitProtoToolSummaryString", ToolKit.ToolKitProtoToolSummaryString.self),
    NativeMessageType("ToolKitProtoToolSummaryString.Component", ToolKit.ToolKitProtoToolSummaryString.Component.self),
    NativeMessageType("ToolKitProtoToolboxDump", ToolKit.ToolKitProtoToolboxDump.self),
    NativeMessageType("ToolKitProtoToolboxDump.Metadata", ToolKit.ToolKitProtoToolboxDump.Metadata.self),
    NativeMessageType("ToolKitProtoTriggerDefinition", ToolKit.ToolKitProtoTriggerDefinition.self),
    NativeMessageType("ToolKitProtoTriggerDefinition.Version1", ToolKit.ToolKitProtoTriggerDefinition.Version1.self),
    NativeMessageType("ToolKitProtoTypeDefinition", ToolKit.ToolKitProtoTypeDefinition.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1", ToolKit.ToolKitProtoTypeDefinition.Version1.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Codable", ToolKit.ToolKitProtoTypeDefinition.Version1.Codable.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Entity", ToolKit.ToolKitProtoTypeDefinition.Version1.Entity.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Entity.Property", ToolKit.ToolKitProtoTypeDefinition.Version1.Entity.Property.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Entity.Property.SpotlightAttributes", ToolKit.ToolKitProtoTypeDefinition.Version1.Entity.Property.SpotlightAttributes.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Enumeration", ToolKit.ToolKitProtoTypeDefinition.Version1.Enumeration.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Enumeration.Case", ToolKit.ToolKitProtoTypeDefinition.Version1.Enumeration.Case.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Query", ToolKit.ToolKitProtoTypeDefinition.Version1.Query.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Query.PredicateTemplates", ToolKit.ToolKitProtoTypeDefinition.Version1.Query.PredicateTemplates.self),
    NativeMessageType("ToolKitProtoTypeDefinition.Version1.Query.PredicateTemplates.PredicateMetadata", ToolKit.ToolKitProtoTypeDefinition.Version1.Query.PredicateTemplates.PredicateMetadata.self),
    NativeMessageType("ToolKitProtoTypeDisplayRepresentation", ToolKit.ToolKitProtoTypeDisplayRepresentation.self),
    NativeMessageType("ToolKitProtoTypeIdentifier", ToolKit.ToolKitProtoTypeIdentifier.self),
    NativeMessageType("ToolKitProtoTypeIdentifier.Attributed", ToolKit.ToolKitProtoTypeIdentifier.Attributed.self),
    NativeMessageType("ToolKitProtoTypeIdentifier.Builtin", ToolKit.ToolKitProtoTypeIdentifier.Builtin.self),
    NativeMessageType("ToolKitProtoTypeIdentifier.Codable", ToolKit.ToolKitProtoTypeIdentifier.Codable.self),
    NativeMessageType("ToolKitProtoTypeIdentifier.Custom", ToolKit.ToolKitProtoTypeIdentifier.Custom.self),
    NativeMessageType("ToolKitProtoTypeIdentifier.Primitive", ToolKit.ToolKitProtoTypeIdentifier.Primitive.self),
    NativeMessageType("ToolKitProtoTypeInstance", ToolKit.ToolKitProtoTypeInstance.self),
    NativeMessageType("ToolKitProtoTypeInstance.Constrained", ToolKit.ToolKitProtoTypeInstance.Constrained.self),
    NativeMessageType("ToolKitProtoTypeInstance.Deferred", ToolKit.ToolKitProtoTypeInstance.Deferred.self),
    NativeMessageType("ToolKitProtoTypeInstance.Optional", ToolKit.ToolKitProtoTypeInstance.Optional.self),
    NativeMessageType("ToolKitProtoTypeInstance.Restricted", ToolKit.ToolKitProtoTypeInstance.Restricted.self),
    NativeMessageType("ToolKitProtoTypeInstance.Union", ToolKit.ToolKitProtoTypeInstance.Union.self),
    NativeMessageType("ToolKitProtoTypedValue", ToolKit.ToolKitProtoTypedValue.self),
    NativeMessageType("ToolKitProtoTypedValue.CodableValue", ToolKit.ToolKitProtoTypedValue.CodableValue.self),
    NativeMessageType("ToolKitProtoTypedValue.CollectionValue", ToolKit.ToolKitProtoTypedValue.CollectionValue.self),
    NativeMessageType("ToolKitProtoTypedValue.DeferredValue", ToolKit.ToolKitProtoTypedValue.DeferredValue.self),
    NativeMessageType("ToolKitProtoTypedValue.DeferredValue.Storage", ToolKit.ToolKitProtoTypedValue.DeferredValue.Storage.self),
    NativeMessageType("ToolKitProtoTypedValue.DeferredValue.Storage.ActionParameterDefaultValueStorage", ToolKit.ToolKitProtoTypedValue.DeferredValue.Storage.ActionParameterDefaultValueStorage.self),
    NativeMessageType("ToolKitProtoTypedValue.DeferredValue.Storage.ContentItemPropertyStorage", ToolKit.ToolKitProtoTypedValue.DeferredValue.Storage.ContentItemPropertyStorage.self),
    NativeMessageType("ToolKitProtoTypedValue.DeferredValue.Storage.EntityPropertyStorage", ToolKit.ToolKitProtoTypedValue.DeferredValue.Storage.EntityPropertyStorage.self),
    NativeMessageType("ToolKitProtoTypedValue.EntityIdentifierValue", ToolKit.ToolKitProtoTypedValue.EntityIdentifierValue.self),
    NativeMessageType("ToolKitProtoTypedValue.EntityValue", ToolKit.ToolKitProtoTypedValue.EntityValue.self),
    NativeMessageType("ToolKitProtoTypedValue.EntityValue.ProtocolPropertyMap", ToolKit.ToolKitProtoTypedValue.EntityValue.ProtocolPropertyMap.self),
    NativeMessageType("ToolKitProtoTypedValue.EnumerationValue", ToolKit.ToolKitProtoTypedValue.EnumerationValue.self),
    NativeMessageType("ToolKitProtoTypedValue.ID", ToolKit.ToolKitProtoTypedValue.ID.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.App", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.App.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.CurrencyAmount", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.CurrencyAmount.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.DateComponents", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.DateComponents.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.DateComponents.Calendar", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.DateComponents.Calendar.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.DateInterval", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.DateInterval.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Decimal", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Decimal.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Decimal.Mantissa", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Decimal.Mantissa.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Duration", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Duration.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.File", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.File.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Measurement", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Measurement.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.PaymentMethod", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.PaymentMethod.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Person", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Person.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Person.Handle", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Person.Handle.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Person.NameComponents", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Person.NameComponents.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Person.NameComponents.PhoneticRepresentation", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Person.NameComponents.PhoneticRepresentation.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Placemark", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Placemark.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleEnd", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleEnd.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleMonth", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleMonth.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleWeekday", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleWeekday.self),
    NativeMessageType("ToolKitProtoTypedValue.PrimitiveValue.Shortcut", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Shortcut.self),
    NativeMessageType("ToolKitProtoTypedValue.Provenance", ToolKit.ToolKitProtoTypedValue.Provenance.self),
    NativeMessageType("ToolKitProtoTypedValue.QueryValue", ToolKit.ToolKitProtoTypedValue.QueryValue.self),
    NativeMessageType("ToolKitProtoTypedValueResolvable", ToolKit.ToolKitProtoTypedValueResolvable.self),
    NativeMessageType("ToolKitProtoUniquePredicate", ToolKit.ToolKitProtoUniquePredicate.self),
    NativeMessageType("ToolKitProtoVacuumOperationEnd", ToolKit.ToolKitProtoVacuumOperationEnd.self),
    NativeMessageType("ToolKitProtoVacuumOperationStart", ToolKit.ToolKitProtoVacuumOperationStart.self),
    NativeMessageType("ToolKitProtoValidPredicate", ToolKit.ToolKitProtoValidPredicate.self),
    NativeMessageType("ToolKitProtoValueSearchPredicate", ToolKit.ToolKitProtoValueSearchPredicate.self),
    NativeMessageType("ToolKitProtoValueSearchPredicate.Template", ToolKit.ToolKitProtoValueSearchPredicate.Template.self),
    NativeMessageType("ToolKitProtoWALOperationEnd", ToolKit.ToolKitProtoWALOperationEnd.self),
    NativeMessageType("ToolKitProtoWALOperationStart", ToolKit.ToolKitProtoWALOperationStart.self),
]

let nativeEnumTypes: [NativeEnumType] = [
    NativeEnumType("ToolKitProtoAppDefinition.Origin", ToolKit.ToolKitProtoAppDefinition.Origin.self),
    NativeEnumType("ToolKitProtoCoercionDefinition.CoercionDirection", ToolKit.ToolKitProtoCoercionDefinition.CoercionDirection.self),
    NativeEnumType("ToolKitProtoCompoundPredicate.Operator", ToolKit.ToolKitProtoCompoundPredicate.Operator.self),
    NativeEnumType("ToolKitProtoContainerDefinition.Origin", ToolKit.ToolKitProtoContainerDefinition.Origin.self),
    NativeEnumType("ToolKitProtoContainerDefinition.TypeEnum", ToolKit.ToolKitProtoContainerDefinition.TypeEnum.self),
    NativeEnumType("ToolKitProtoDisplayRepresentation.DisplayValue.DisplayValueEnum", ToolKit.ToolKitProtoDisplayRepresentation.DisplayValue.DisplayValueEnum.self),
    NativeEnumType("ToolKitProtoIndexingStep.Phase", ToolKit.ToolKitProtoIndexingStep.Phase.self),
    NativeEnumType("ToolKitProtoModelRepresentation.RepresentationComponent.Label.Kind", ToolKit.ToolKitProtoModelRepresentation.RepresentationComponent.Label.Kind.self),
    NativeEnumType("ToolKitProtoModelRepresentationComponentKind", ToolKit.ToolKitProtoModelRepresentationComponentKind.self),
    NativeEnumType("ToolKitProtoModelRepresentationLevel", ToolKit.ToolKitProtoModelRepresentationLevel.self),
    NativeEnumType("ToolKitProtoPushDonationStart.DonationType", ToolKit.ToolKitProtoPushDonationStart.DonationType.self),
    NativeEnumType("ToolKitProtoQuery.SortOrder", ToolKit.ToolKitProtoQuery.SortOrder.self),
    NativeEnumType("ToolKitProtoRestrictionContext.CharacterTypedWith.ParameterMode", ToolKit.ToolKitProtoRestrictionContext.CharacterTypedWith.ParameterMode.self),
    NativeEnumType("ToolKitProtoRestrictionContext.DateExpressibleAs", ToolKit.ToolKitProtoRestrictionContext.DateExpressibleAs.self),
    NativeEnumType("ToolKitProtoRestrictionContext.PersonReachableAs", ToolKit.ToolKitProtoRestrictionContext.PersonReachableAs.self),
    NativeEnumType("ToolKitProtoRestrictionContext.TextTypedWith.AutocorrectionType", ToolKit.ToolKitProtoRestrictionContext.TextTypedWith.AutocorrectionType.self),
    NativeEnumType("ToolKitProtoRestrictionContext.TextTypedWith.CapitalizationType", ToolKit.ToolKitProtoRestrictionContext.TextTypedWith.CapitalizationType.self),
    NativeEnumType("ToolKitProtoRestrictionContext.TextTypedWith.KeyboardType", ToolKit.ToolKitProtoRestrictionContext.TextTypedWith.KeyboardType.self),
    NativeEnumType("ToolKitProtoRuntimePlatform", ToolKit.ToolKitProtoRuntimePlatform.self),
    NativeEnumType("ToolKitProtoRuntimeRequirement.DeviceCapability.DeviceCapabilityType", ToolKit.ToolKitProtoRuntimeRequirement.DeviceCapability.DeviceCapabilityType.self),
    NativeEnumType("ToolKitProtoRuntimeRequirement.DeviceState", ToolKit.ToolKitProtoRuntimeRequirement.DeviceState.self),
    NativeEnumType("ToolKitProtoSystemToolProtocol.AgentIntent.SupportedFeature", ToolKit.ToolKitProtoSystemToolProtocol.AgentIntent.SupportedFeature.self),
    NativeEnumType("ToolKitProtoSystemToolProtocol.IntentSideEffect.Behavior.Kind", ToolKit.ToolKitProtoSystemToolProtocol.IntentSideEffect.Behavior.Kind.self),
    NativeEnumType("ToolKitProtoToolDefinition.Version1.AuthenticationPolicy", ToolKit.ToolKitProtoToolDefinition.Version1.AuthenticationPolicy.self),
    NativeEnumType("ToolKitProtoToolDefinition.Version1.Flag", ToolKit.ToolKitProtoToolDefinition.Version1.Flag.self),
    NativeEnumType("ToolKitProtoToolDefinition.Version1.Parameter.ParameterFlags", ToolKit.ToolKitProtoToolDefinition.Version1.Parameter.ParameterFlags.self),
    NativeEnumType("ToolKitProtoToolDefinition.Version1.ToolIcon.ToolSymbolIconStyle", ToolKit.ToolKitProtoToolDefinition.Version1.ToolIcon.ToolSymbolIconStyle.self),
    NativeEnumType("ToolKitProtoToolDefinition.Version1.ToolType", ToolKit.ToolKitProtoToolDefinition.Version1.ToolType.self),
    NativeEnumType("ToolKitProtoToolDefinition.Version1.VisibilityFlag", ToolKit.ToolKitProtoToolDefinition.Version1.VisibilityFlag.self),
    NativeEnumType("ToolKitProtoToolInvocationOptions.AccessLevel", ToolKit.ToolKitProtoToolInvocationOptions.AccessLevel.self),
    NativeEnumType("ToolKitProtoToolInvocationOptions.AssistantDismissalPolicy", ToolKit.ToolKitProtoToolInvocationOptions.AssistantDismissalPolicy.self),
    NativeEnumType("ToolKitProtoToolInvocationOptions.ConfirmationConditions", ToolKit.ToolKitProtoToolInvocationOptions.ConfirmationConditions.self),
    NativeEnumType("ToolKitProtoToolInvocationOptions.InteractionMode", ToolKit.ToolKitProtoToolInvocationOptions.InteractionMode.self),
    NativeEnumType("ToolKitProtoToolInvocationOptions.InterfaceIdiom", ToolKit.ToolKitProtoToolInvocationOptions.InterfaceIdiom.self),
    NativeEnumType("ToolKitProtoTriggerDefinition.Version1.Flag", ToolKit.ToolKitProtoTriggerDefinition.Version1.Flag.self),
    NativeEnumType("ToolKitProtoTypeDefinition.Version1.Entity.AuthenticationPolicy", ToolKit.ToolKitProtoTypeDefinition.Version1.Entity.AuthenticationPolicy.self),
    NativeEnumType("ToolKitProtoTypeDefinition.Version1.Entity.RuntimeFlags", ToolKit.ToolKitProtoTypeDefinition.Version1.Entity.RuntimeFlags.self),
    NativeEnumType("ToolKitProtoTypeDefinition.Version1.Enumeration.Kind", ToolKit.ToolKitProtoTypeDefinition.Version1.Enumeration.Kind.self),
    NativeEnumType("ToolKitProtoTypeIdentifier.Primitive.MeasurementUnitType", ToolKit.ToolKitProtoTypeIdentifier.Primitive.MeasurementUnitType.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.DateComponents.CalendarIdentifier", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.DateComponents.CalendarIdentifier.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.Decimal.Sign", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Decimal.Sign.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.PaymentMethod.TypeEnum", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.PaymentMethod.TypeEnum.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.Person.Handle.TypeEnum", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Person.Handle.TypeEnum.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.Placemark.TypeEnum", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.Placemark.TypeEnum.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.CalendarMatchingPolicy", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.CalendarMatchingPolicy.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.CalendarRepeatedTimePolicy", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.CalendarRepeatedTimePolicy.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.LocaleWeekday", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.LocaleWeekday.self),
    NativeEnumType("ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleFrequency", ToolKit.ToolKitProtoTypedValue.PrimitiveValue.RecurrenceRule.RecurrenceRuleFrequency.self),
]
